version: "3.3"

services:
    php:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - 8000:8000
        volumes:
            - ./..:/app

    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: content_back
            POSTGRES_PASSWORD: content_back

    redis:
        image: redis:6

    adminer:
        image: adminer
        ports:
            - 8001:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
